export interface ScamLibraryEntry {
  id: string
  name: string
  targets: string
  setup: string
  example: string
  redFlags: string[]
  safeAction: string
  relatedLessonId: string
  practiceLink: string
  category: string
}

export const scamLibraryEntries: ScamLibraryEntry[] = [
  {
    id: "phishing",
    name: "Phishing",
    targets: "Anyone with email, text messages, or social media accounts",
    setup: "A message pushes you to click a link, sign in, or verify information.",
    example: "Your account needs review. Sign in before access expires today.",
    redFlags: ["Unexpected link", "Urgent wording", "Login or verification request"],
    safeAction: "Open the official app or type the real website yourself.",
    relatedLessonId: "phishing-fake-websites",
    practiceLink: "/scam-lab",
    category: "Account scams",
  },
  {
    id: "fake-bank-alert",
    name: "Fake Bank Alert",
    targets: "Bank and payment app users",
    setup: "A message claims your account is locked or has unusual activity.",
    example: "Bank alert: verify now or your account will be suspended.",
    redFlags: ["Threat of suspension", "Message link", "Requests codes or card details"],
    safeAction: "Use the official banking app or call the number on your card.",
    relatedLessonId: "phishing-fake-websites",
    practiceLink: "/scam-lab",
    category: "Money scams",
  },
  {
    id: "fake-delivery-text",
    name: "Fake Delivery Text",
    targets: "Online shoppers and phone users",
    setup: "A package text asks for a small fee or address confirmation.",
    example: "Package held. Pay $0.30 today to avoid return.",
    redFlags: ["Tiny fee", "Unfamiliar link", "Deadline pressure"],
    safeAction: "Check tracking through the carrier or store website.",
    relatedLessonId: "phishing-fake-websites",
    practiceLink: "/scam-lab",
    category: "Message scams",
  },
  {
    id: "fake-job-offer",
    name: "Fake Job Offer",
    targets: "Students, job seekers, and remote workers",
    setup: "A recruiter offers easy work, high pay, or immediate hiring.",
    example: "You are selected for a remote role. Pay the equipment fee today.",
    redFlags: ["No interview", "Upfront fee", "Unusual payment method"],
    safeAction: "Verify through the company's official careers page.",
    relatedLessonId: "payment-money-scams",
    practiceLink: "/scam-lab",
    category: "Job scams",
  },
  {
    id: "fake-toll-text",
    name: "Fake Toll or Traffic Fine Text",
    targets: "Drivers",
    setup: "A text claims you owe a small toll or fine with a large penalty.",
    example: "Unpaid toll balance $4.35. Pay now to avoid a $75 penalty.",
    redFlags: ["Small balance", "Penalty threat", "Payment link"],
    safeAction: "Use the official toll authority website.",
    relatedLessonId: "phishing-fake-websites",
    practiceLink: "/scam-lab",
    category: "Money scams",
  },
  {
    id: "romance-investment",
    name: "Romance or Investment Scam",
    targets: "People using dating, social, or messaging apps",
    setup: "A friendly or romantic contact slowly introduces crypto, trading, or emergency money.",
    example: "I trust you. My mentor has a private investment group opening tonight.",
    redFlags: ["Fast emotional trust", "Private platform", "Crypto or money request"],
    safeAction: "Do not invest through someone you met online.",
    relatedLessonId: "social-engineering",
    practiceLink: "/scam-lab",
    category: "Social media scams",
  },
  {
    id: "tech-support",
    name: "Tech Support Scam",
    targets: "Computer and phone users",
    setup: "A warning or caller says your device is infected and asks for remote access.",
    example: "Download this support tool so we can secure your computer.",
    redFlags: ["Unexpected warning", "Remote access request", "Download link"],
    safeAction: "Use official device support or a trusted local helper.",
    relatedLessonId: "device-app-safety",
    practiceLink: "/scam-lab",
    category: "Account scams",
  },
  {
    id: "gift-card",
    name: "Gift Card Scam",
    targets: "Families, employees, and shoppers",
    setup: "Someone asks you to buy gift cards and send the codes.",
    example: "Buy Apple gift cards and text me the numbers right away.",
    redFlags: ["Gift card payment", "Secrecy", "Urgency"],
    safeAction: "Do not buy gift cards as payment for a request.",
    relatedLessonId: "payment-money-scams",
    practiceLink: "/scam-lab",
    category: "Money scams",
  },
  {
    id: "gaming-account",
    name: "Gaming Account Warning",
    targets: "Children, teens, and gamers",
    setup: "A message claims a gaming account will be banned unless the user verifies quickly.",
    example: "Your game account will be removed. Send your login code to appeal.",
    redFlags: ["Threat of losing account", "Code request", "Unofficial support"],
    safeAction: "Use the official game support page and ask a trusted adult.",
    relatedLessonId: "passwords-mfa-account-safety",
    practiceLink: "/scam-lab",
    category: "Social media scams",
  },
  {
    id: "family-emergency",
    name: "Family Emergency Scam",
    targets: "Parents, grandparents, and families",
    setup: "Someone claims to be family in trouble and asks for money or secrecy.",
    example: "I'm in trouble. Please don't call anyone. Send money now.",
    redFlags: ["Scary story", "Secrecy", "Money request"],
    safeAction: "Call the person on a known number and ask another family member.",
    relatedLessonId: "social-engineering",
    practiceLink: "/family-practice",
    category: "Family scams",
  },
  {
    id: "marketplace-buyer",
    name: "Fake Marketplace Buyer",
    targets: "People selling items online",
    setup: "A buyer sends too much money or asks for a refund before payment clears.",
    example: "I sent extra by mistake. Send the difference back through Zelle.",
    redFlags: ["Overpayment", "Payment app pressure", "Pickup person story"],
    safeAction: "Use protected marketplace payments and wait for verified payment.",
    relatedLessonId: "payment-money-scams",
    practiceLink: "/scam-lab",
    category: "Money scams",
  },
  {
    id: "fake-refund",
    name: "Fake Refund Scam",
    targets: "Subscription and online shoppers",
    setup: "A fake invoice or refund notice pushes you to call or share card information.",
    example: "Your plan renewed for $399. Call today for a refund.",
    redFlags: ["Unexpected invoice", "Phone number in message", "Card info request"],
    safeAction: "Check the real account directly and do not call numbers from the message.",
    relatedLessonId: "payment-money-scams",
    practiceLink: "/scam-lab",
    category: "Money scams",
  },
  {
    id: "fake-qr",
    name: "Fake QR Code",
    targets: "Parking, restaurant, and event users",
    setup: "A QR code hides an unsafe payment or login destination.",
    example: "A sticker QR code on a parking sign opens an unfamiliar payment page.",
    redFlags: ["Sticker over original code", "Unknown domain", "Payment request"],
    safeAction: "Use the official app, website, or posted payment machine.",
    relatedLessonId: "phishing-fake-websites",
    practiceLink: "/scam-lab",
    category: "Message scams",
  },
  {
    id: "fake-prize",
    name: "Fake Prize or Reward",
    targets: "Shoppers and social media users",
    setup: "A message says you won something but must pay or verify to claim it.",
    example: "You won a reward card. Pay shipping to claim today.",
    redFlags: ["Prize you did not enter", "Fee to claim", "Personal information request"],
    safeAction: "Do not pay to receive a prize. Verify through the brand's official website.",
    relatedLessonId: "payment-money-scams",
    practiceLink: "/scam-lab",
    category: "Money scams",
  },
]

export const scamLibraryCategories = Array.from(new Set(scamLibraryEntries.map((entry) => entry.category)))
